autoDetectedPackages:
- com.xhf.learning.httpclient
- com.xhf.learning.okhttp
- com.xhf.learning.store
- com.xhf.learning.ui
- com.xhf.leetcode.plugin.actions
- com.xhf.leetcode.plugin.editors
- com.xhf.leetcode.plugin.icons
- com.xhf.leetcode.plugin.io.console
- com.xhf.leetcode.plugin.io.file
- com.xhf.leetcode.plugin.io.http
- com.xhf.leetcode.plugin.manager
- com.xhf.leetcode.plugin.model
- com.xhf.leetcode.plugin.service
- com.xhf.leetcode.plugin.setting
- com.xhf.leetcode.plugin.utils
- com.xhf.leetcode.plugin.window
enableAutoDetect: true
ignoreSameClassCall: null
ignoreSamePackageCall: null
includedPackagePrefixes: null
includedParentClasses: null
name: xcodemap-filter
